FROM registry.redhat.io/rhel9/rhel-bootc:latest

RUN <<EOF
dnf -y groupinstall 'Workstation' --exclude=firefox
dnf clean all
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install -y flathub org.mozilla.firefox
systemctl set-default graphical.target
EOF

RUN bootc container lint
